### ISSUE TITLE
OAuth2.Login problem

### ISSUE THREAD

**Issue by kindermannhubert** [prayzzz/SoundCloud.Api#1]
I was stuck for few hours on problem with using OAuth2.Login(Credentials credentials) method and i think there is a bug.

When you have following code:

``` C#
var client = SoundCloudClient.CreateUnauthorized("XXX");
var credentials = new Credentials()
{
    client_id = "XXX",
    client_secret = "XXX",
    username = "XXX",
    password = "XXX"
};

var loginResult = client.OAuth2.Login(credentials);
```

where "XXX" are correct values, then the resulting access token (=loginResult.Data.access_token) is missing one part. It is in form:
"x-xxxxxx--xxxxxxxxxxxxxxxxxxxxxx".
This token can be used for creation of new client:

``` C#
client = SoundCloudClient.CreateAuthorized(loginResult.Data.access_token);
```

and for example this code works as expected:

``` C#
client.Tracks.Get().First()
```

but this code returns null:

``` C#
var me = client.Me.Get();
```

All works as expected only, if line in the Login method is changed from:

``` C#
return Create<Credentials>(builder.BuildUri(), credentials.ToClientCredentialsParameters(GrantType.ClientCredentials));
```

to

``` C#
return Create<Credentials>(builder.BuildUri(), credentials.ToClientCredentialsParameters(GrantType.Password));
```

Also after this change the resulting token has format:
"x-xxxxxx-xxxxxxxxx-xxxxxxxxxxxxx".

Is presented change to Login method correct?
Could you please look at it?

**Comment by prayzzz** [comment]
Thanks for reporting this issue!
This issue should be fixed with the now available 1.1 release.

**Comment by zelexis** [comment]
Is this working? I cannot get an authorised login to work at all. I've tried both OAuth2.LoginAsync and OAuth2.ClientCredentialsAsync, with valid credentials, and always get a response status of "unauthorised".

**Comment by prayzzz** [comment]
It's currently broken.  I didn't invest any time in this part of the API when working on the 2.0.0 release, since the app registration by SoundCloud is closed. I have it back working locally. Let's track this progress in a separate issue #6.
