### ISSUE TITLE
Linked Partitioning?

### ISSUE THREAD

**Issue by zelexis** [prayzzz/SoundCloud.Api#5]
Hello, this seems to still use the old paging method of Limit and Offset, which does not work anymore. If you try to increment the offset, you always get the same set of results, it does not page forward.

SoundCloud replaced this method with linked partitioning in 2015.
https://developers.soundcloud.com/blog/offset-pagination-deprecated
Any plans to update this code to do it the new way?

Thanks.

**Comment by prayzzz** [comment]
Hi,

linked partitioning doesn't seem to do something else than increment the `offeset` parameter.
This is the result when following the `next_href` manually:
```
Initial:
https://api.soundcloud.com/tracks?linked_partitioning=1&client_id=...&q=Major%20Lazer&limit=10

Next:
https://api.soundcloud.com/tracks?linked_partitioning=1&client_id=...&offset=10&q=Major%20Lazer&limit=10
https://api.soundcloud.com/tracks?linked_partitioning=1&client_id=...&offset=20&q=Major%20Lazer&limit=10
https://api.soundcloud.com/tracks?linked_partitioning=1&client_id=...&offset=30&q=Major%20Lazer&limit=10
```

Am I missing something?

Besides that, there was an Issue, that the  `offset` was not appended to the URL.
I fixed that in [2.0.1](https://github.com/prayzzz/SoundCloud.Api/releases/tag/2.0.1)

**Comment by zelexis** [comment]
Hi, thanks for taking a look. I've just tried 2.0.1, I'm just testing with a simple loop using Me.GetFollowersAsync, and as I increment the offset, it always returns the same results.

**Comment by prayzzz** [comment]
Hm, `next_href` for followers contains a `cursor` parameter.
```
https://api.soundcloud.com/me/followers?oauth_token=...&page_size=1&cursor=1486806931979
```

SoundCloud behaves inconsistent here... thats unfortunate.
I'll need some days to come up with a solution for this.

**Comment by zelexis** [comment]
Much appreciated!

**Comment by prayzzz** [comment]
I pushed `3.0.0-alpha01` to Nuget.
Please check if this fits your needs.

See also: https://github.com/prayzzz/SoundCloud.Api/blob/6a78b9f07bceccbad7ebda0552f3e14fa27c0435/README.md#lists

**Comment by zelexis** [comment]
I've only done a quick initial test with GetFollowersAsync, but it works great, and now returns all the results. Thanks a lot!

**Comment by prayzzz** [comment]
Merged to master. Will be in the 3.0.0 release.
