### ISSUE TITLE
OAuth API not working

### ISSUE THREAD

**Issue by prayzzz** [prayzzz/SoundCloud.Api#6]
Is this working? I cannot get an authorised login to work at all. I've tried both OAuth2.LoginAsync and OAuth2.ClientCredentialsAsync, with valid credentials, and always get a response status of "unauthorised".

_Originally posted by @zelexis in https://github.com/prayzzz/SoundCloud.Api/issues/1#issuecomment-488781706_

**Comment by zelexis** [comment]
Working now :)

**Comment by prayzzz** [comment]
I added `3.0.0-alpha02` with a `SoundCloudOAuth` class to perform a OAuth flow before creating the client.

**Comment by prayzzz** [comment]
Released 3.0.0.
